#!/usr/bin/python3

import tkinter as tk
import random
import sys
import time

#やり直す!!!

#窓の初期設定
root = tk.Tk()
root.title("Window Game")
root.geometry("1000x1000+0+0")
#レベル取得
level = int(sys.stdin.read().strip())
#ダミーによるゲームオーバー
gameover = 0

# 画面サイズ取得
max_width  = root.winfo_screenwidth()  -1000
max_height = root.winfo_screenheight() -1000


#ボタン設定

def pushed():
#テスト
 print("true")
 global level
#レベル毎のボタン縮小(5段階)
 if level >= 5:
    button.config(width =8, height =8)
    if level >= 10:
       button.config(width =6, height =6)
       if level >= 15:
          button.config(width =5, height =5)
          if level >= 20:
             button.config(width =4, height =4)
             if level >= 25:
                button.config(width =3, height =3)
#窓の場所もランダムに
 if level >= 30:
    rw = random.randint(0, max_width)
    rh = random.randint(0, max_height)
    root.geometry(f"1000x1000+{rw}+{rh}")

#ダミー出現(2段階)
 if level >= 35:
    pass
    if level >= 50:
       pass
#ダミー押したら終了
 if gameover == 1:
    pass
 level += 1
 bx = random.randint(0, 950)
 by = random.randint(0, 950)
 button.place(x =bx, y =by)
 button.config(text =int(level))


def timer():
 global count
 count += 1
 min, sec = divmod(count, 60)
 count.config(text =f"{min}:{sec}")
 count.after(1000, timer)


#スタートボタン(中央に揃えたい)
button = tk.Button(root, text ="start!!", command = pushed)
button.place(x =500, y=500)
button.config(width =15, height =3)
#画面内にタイマーぶち込み隊


#窓を持続して表示
root.mainloop()
