#!/usr/bin/python3

import tkinter as tk
import random

cr =76

def pushed():
 print("click!")
# button.destroy()
 bx = random.randint(0, 900)
 by = random.randint(0, 900)
 cr = random.randint(65, 90)

 button = tk.Button(root, text=chr(cr), command=pushed)
 button.place(x =bx, y =by)
root = tk.Tk()
root.title("Window Game")
root.geometry("1000x1000+0+0")

#表示
button = tk.Button(root, text=chr(cr), command=pushed)
button.place(x =500, y=500)

# 実行
root.mainloop()
